### PR TITLE
Fix generation of selection merges

### LINKED ISSUE #448: fails new SPIR-V validation when compiling test/global-variable-no-undef-initializer.cl
When updating SPIRV-Tools, I get a validation error on one of the tests, test/global-variable-no-undef-initializer.cl  :

error: line 81: Header block 55[%55] is contained in the loop construct headed by 51[%51], but it's merge block 61[%61] is not
  %55 = OpLabel

### PR DESCRIPTION
**Pull request by alan-baker**
Fixes #448

* Refactor structured order computation into a new file
* updates deps
* Modify SPIRVProducer pass to figure out merge and continues at the
start of the pass
  * this is based on traversing in structured order
  * do not generate selection merges if one side of the branch is a loop
  continue or merge
* add a new test

The SPIRV-Tools update also includes the new validator check.

ComputeStructuredOrder is effectively a move from ReorderBasicBlock::StructuredOrder.

### CODE REVIEW

File: lib/SPIRVProducerPass.cpp [hunk 1]
```diff
@@ -4768,42 +4778,7 @@ void SPIRVProducerPass::HandleDeferredInstruction() {
           getAnalysis<LoopInfoWrapperPass>(*Func).getLoopInfo();
 
       BasicBlock *BrBB = Br->getParent();
-      Loop *L = LI.getLoopFor(BrBB);
```
Comment (alan-baker) [inline lib/SPIRVProducerPass.cpp]: This effectively moved to PopulateStructuredCFGMaps below.

File: lib/SPIRVProducerPass.cpp [hunk 2]
```diff
@@ -5915,3 +5878,87 @@ bool SPIRVProducerPass::CalledWithCoherentResource(Argument &Arg) {
...
+          BasicBlock *Header = L->getHeader();
+          BasicBlock *Latch = L->getLoopLatch();
+          for (auto *loop_block : L->blocks()) {
+            if (loop_block == Header) {
+              continue;
+            }
+
+            // Check whether block dominates block with back-edge.
+            if (DT.dominates(loop_block, Latch)) {
+              ContinueBB = loop_block;
```
Comment (dneto0) [inline lib/SPIRVProducerPass.cpp]: Also need the backedge block to post-dominate the continue target.
How do we know that will be satisfied as well?

Comment (dneto0) [reply lib/SPIRVProducerPass.cpp]: Hmm. Seems like this is a consequence of the StructurizeCFG algorithm?
Needs a comment at least.

File: lib/SPIRVProducerPass.cpp [hunk 3]
```diff
@@ -4768,42 +4778,7 @@ void SPIRVProducerPass::HandleDeferredInstruction() {
           getAnalysis<LoopInfoWrapperPass>(*Func).getLoopInfo();
```
Comment (dneto0) [inline lib/SPIRVProducerPass.cpp]: You no longer need these three variables: Func, DT, LI
