### PR TITLE
Expand functionality to catch odd truncates

### LINKED ISSUE #583: Invalid integer widths from mask + switch
Compiling this kernel generates SPIR-V that uses 2-bit integers:
```
kernel void foo(global float *output)
{
  size_t i = get_global_id(0);

  float result = 0.f;
  switch (i & 0x3) {
    case 1:
      result = 2.f;
      break;
    case 2:
      result = 4.f;
      break;
  }

  output[i] = result;
}
```

Commands:
```
$ bin/clspv foo.cl
$ spirv-val a.spv 
error: line 26: Invalid number of bits (2) used for OpTypeInt.
  %u2 = OpTypeInt 2 0
```

### PR DESCRIPTION
**Pull request by alan-baker**
Fixes #583

* Changes UndoTruncatedSwitchPass to look for truncates to look for
truncates to non-power-of-2 integer sizes instead of switches on odd
sizes
  * rename pass
  * new logic to update instructions that aren't full rewritten
  * new tests

The first commit has the heart of the changes. The second commit just renames things.

### CODE REVIEW

File: lib/UndoTruncateToOddIntegerPass.cpp [hunk 1]
```diff
@@ -160,32 +206,50 @@ bool UndoTruncatedSwitchConditionPass::runOnModule(Module &M) {
...
+          WorkList.push_back(user_inst);
+        }
+      }
     }
   }
 
-  // Remove the zombies if we can.  We expect to.  They are ordered from
-  // combinations down to their supporting values.
+  // Remove the zombies if we can.  We expect to. Generally this can be done in
+  // 1 or 2 passes.
```
Comment (jrprice) [inline lib/UndoTruncateToOddIntegerPass.cpp:226]: I couldn't come with a scenario where we *wouldn't* be able to remove all zombie instructions (i.e. no instruction that is replaced should ever still have users).

Since we're doing the replacement recursively, can't we just build a stack of instructions to remove and then do them all bottom up (in one pass)? I just hacked this into your changes and they worked fine for all existing tests. If not, we're missing test coverage for the case where this doesn't work.

Comment (alan-baker) [reply lib/UndoTruncateToOddIntegerPass.cpp:226]: Hmm I think I must have tested it wrong in development because UniqueVector indexing starts at 1.

File: lib/UndoTruncateToOddIntegerPass.cpp [hunk 2]
```diff
@@ -160,31 +206,28 @@ bool UndoTruncatedSwitchConditionPass::runOnModule(Module &M) {
...
 
-  // Remove the zombies if we can.  We expect to.  They are ordered from
-  // combinations down to their supporting values.
-  for (auto *zombie : zombies_) {
-    if (!zombie->hasNUsesOrMore(1)) {
+  // Remove the zombies if we can.  We expect to. We've ordered zombies in
+  // reverse.
+  for (int i = zombies_.size(); i >= 1; --i) {
+    auto zombie = zombies_[i];
+    if (!zombie->hasNUsesOrMore(1))
```
Comment (jrprice) [inline lib/UndoTruncateToOddIntegerPass.cpp:229]: Arguably this should just be an assertion; if there's still uses then something has gone wrong.

**Comment by alan-baker** [comment]
I didn't change zero extend, but yes it does look incorrect.

**Comment by alan-baker** [comment]
I've made changes to fix zext handling and other integer sizes.

File: lib/UndoTruncateToOddIntegerPass.cpp [hunk 3]
```diff
@@ -56,44 +58,45 @@ struct UndoTruncateToOddIntegerPass : public ModulePass {
...
+              (uint32_t)APInt::getAllOnesValue(bit_width).getZExtValue()),
           "", trunc);
     } else if (auto *zext = dyn_cast<ZExtInst>(v)) {
-      result = new ZExtInst(zext->getOperand(0), i32_, "", zext);
+      auto tmp = ZeroExtend(zext->getOperand(0), desired_bit_width);
+      auto operand_bit_width = tmp->getType()->getIntegerBitWidth();
+      if (isPowerOf2_32(operand_bit_width)) {
+        result = tmp;
+      } else {
+        result = new ZExtInst(zext->getOperand(0), desired_int_ty, "", zext);
```
Comment (jrprice) [inline lib/UndoTruncateToOddIntegerPass.cpp:86]: I don't quite understand what situation this code is handling. When is `result = tmp` not the right thing to do? Doesn't `ZeroExtend()` always produce a result with the desired bit width? I couldn't come up with a sequence of instructions that triggers the `else` clause.

Comment (alan-baker) [reply lib/UndoTruncateToOddIntegerPass.cpp]: I've reworked this and added a few tests with mixed sizes that need extended (not all 32-bits).
