### PR TITLE
Fix #361 - Initialize clspv passes into the registry.

### LINKED ISSUE #361: -print-{after,before}-all is broken
This was apparently broken by `a4c44fae` (Re-implement clspv-opt as a standalone driver).

### PR DESCRIPTION
**Pull request by dnovillo**
Passes were not registering their print-after/print-before flags.  This calls the pass initializer and adds a test for a clspv pass.

### CODE REVIEW

File: lib/Compiler.cpp [hunk 1]
```diff
@@ -805,6 +805,7 @@ int Compile(const int argc, const char *const argv[]) {
   llvm::PassRegistry &Registry = *llvm::PassRegistry::getPassRegistry();
   llvm::initializeCore(Registry);
   llvm::initializeScalarOpts(Registry);
+  llvm::initializeClspvPasses(Registry);
```
Comment (alan-baker) [inline lib/Compiler.cpp]: This likely needs done in `CompileFromSourceString` too.

Comment (dnovillo) [reply lib/Compiler.cpp]: Sure.  I don't see this function tested anywhere, though.  Are there unit tests I can add to?

**Comment by dnovillo** [comment]
> This list of commits looks strange. Have you rebased recently?

Yeah.  I created a new branch off of an old branch.  Just squashed everything.

**Comment by dnovillo** [comment]
@alan-baker Added a call from `CompileFromSourceString`.  PTAL.

File: lib/Compiler.cpp (hunk 1 above)
Comment (alan-baker) [reply lib/Compiler.cpp]: Not without doing some legwork. That function is for the in process API.
