### PR TITLE
Fixes for pointer cast simplification

### LINKED ISSUE #1113: Crash when compiling kernel from Geekbench 6 Horizon Detection
When compiling the attached source, with the following options:

```
clspv source.cl  -cl-fast-relaxed-math -cl-single-precision-constant  -cl-kernel-arg-info   -fp16=0  -rewrite-packed-structs  -std430-ubo-layout  -decorate-nonuniform    -arch=spir  --use-native-builtins=acos,acosh,acospi,asin,asinh,asinpi,atan,atan2,atan2pi,atanh,atanpi,ceil,copysign,fabs,fdim,floor,fma,fmax,fmin,frexp,half_rsqrt,half_sqrt,isequal,isfinite,isgreater,isgreaterequal,isinf,isless,islessequal,islessgreater,isnan,isnormal,isnotequal,isordered,isunordered,ldexp,mad,rint,round,rsqrt,signbit,sqrt,tanh,trunc,  -spv-version=1.6  -max-pushconstant-size=256  -max-ubo-size=65536  -global-offset  -long-vector  -module-constants-in-storage-buffer  -cl-arm-non-uniform-work-group-size     -o compiled.spv
```

clspv crashes as follows (don't know why the assert is not firing, assertions are enabled):

```
Program received signal SIGSEGV, Segmentation fault.
llvm::GetElementPtrInst::Create (PointeeType=0x55555ae79d98, Ptr=0x55500fa14be0, IdxList=..., NameStr=..., InsertBefore=0x55555b1e6450)
    at /path/to/clvk/external/clspv/third_party/llvm/llvm/include/llvm/IR/Instructions.h:972
972         assert(cast<PointerType>(Ptr->getType()->getScalarType())
(gdb) bt
#0  llvm::GetElementPtrInst::Create (PointeeType=0x55555ae79d98, Ptr=0x55500fa14be0, IdxList=..., NameStr=..., InsertBefore=0x55555b1e6450)
    at /path/to/clvk/external/clspv/third_party/llvm/llvm/include/llvm/IR/Instructions.h:972
#1  0x0000555555ba45e6 in clspv::SimplifyPointerBitcastPass::runOnGEPImplicitCasts (this=<optimized out>, M=...)
    at /path/to/clvk/external/clspv/lib/SimplifyPointerBitcastPass.cpp:490
#2  0x0000555555ba527a in clspv::SimplifyPointerBitcastPass::run (this=0x55555b1be238, M=...) at /path/to/clvk/external/clspv/lib/SimplifyPointerBitcastPass.cpp:52
#3  0x0000555555a89f91 in llvm::detail::PassModel<llvm::Module, clspv::SimplifyPointerBitcastPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (this=<optimized out>, IR=..., AM=...) at /path/to/clvk/external/clspv/third_party/llvm/llvm/include/llvm/IR/PassManagerInternal.h:89
#4  0x000055555906e5a1 in llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (this=<optimized out>, IR=..., 
    AM=...) at /path/to/clvk/external/clspv/third_party/llvm/llvm/include/llvm/IR/PassManager.h:517
#5  0x0000555555aa5458 in (anonymous namespace)::RunPassPipeline (binaryStream=0x7fffffff8b40, M=...) at /path/to/clvk/external/clspv/lib/Compiler.cpp:740
#6  (anonymous namespace)::CompileModule (module=std::unique_ptr<llvm::Module> = {...}, output_buffer=output_buffer@entry=0x0, output_log=0x0, input_filename=...)
    at /path/to/clvk/external/clspv/lib/Compiler.cpp:1101
#7  0x0000555555aa678c in (anonymous namespace)::CompileProgram (input_filename=..., 
    program="// Copyright (C) 2004-2020 Primate Labs Inc.  All Rights Reserved.\r\n\r\n// Matches struct Line in hough.h\r\nstruct Line {\r\n  int theta;\r\n  float rho;\r\n  int score;\r\n};\r\n\r\n// Linear interpolate between (0"..., output_buffer=output_buffer@entry=0x0, output_log=output_log@entry=0x0) at /path/to/clvk/external/clspv/lib/Compiler.cpp:1148
#8  0x0000555555aa7383 in clspv::Compile (argc=<optimized out>, argv=<optimized out>) at /path/to/clvk/external/clspv/lib/Compiler.cpp:1210
#9  0x00007ffff785168a in __libc_start_call_main (main=main@entry=0x5555559f75d0 <main(int, char const* const*)>, argc=argc@entry=20, argv=argv@entry=0x7fffffffca08)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007ffff7851745 in __libc_start_main_impl (main=0x5555559f75d0 <main(int, char const* const*)>, argc=20, argv=0x7fffffffca08, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffc9f8) at ../csu/libc-start.c:360
#11 0x0000555555a88a41 in _start ()
```

[source.txt](https://github.com/google/clspv/files/11491056/source.txt)

### PR DESCRIPTION
**Pull request by alan-baker**
Fixes #1113

* Refactored runOnGEPImplicitCasts into separate functions
  * no longer attempts multiple transforms at the same time
  * refactored methods now iterate deterministically
* Handle a case in GEP index calculation where the heterogeneous struct is larger than the offset of the gep

### CODE REVIEW

File: lib/BitcastUtils.cpp [hunk 1]
```diff
@@ -1091,10 +1085,47 @@ GetIdxsForTyFromOffset(const DataLayout &DataLayout, IRBuilder<> &Builder,
...
+  // TODO: Is there a better way to adjust for this?
+  if (DynVal == nullptr) {
+    if (TyBitWidths.size() == 1 &&
+        (TyBitWidths[0] > CstVal * SmallerBitWidths) && SrcTy->isStructTy()) {
+      // Descending into the aggregate so 0 the first GEP index.
+      if (startIdx == 0)
+        Idxs.push_back(Builder.getInt32(0));
+
+      auto *ty = SrcTy;
+      while (ty->isStructTy() &&
```
Comment (rjodinchr) [inline lib/BitcastUtils.cpp:1097]: I am not sure about this loop, I don't see any test testing it (amongst those you have added. Maybe one already existing does)

**Review by rjodinchr — COMMENTED** [review]
The patch I am working on for #1109 seems to need `runOnCimplicitCasts` and `RunOnUpgradeableConstantCasts` to be merged back together.

**Comment by rjodinchr** [comment]
This is okay to go in, I have [this branch](https://github.com/rjodinchr/clspv/tree/pr/pre-memcpy-fix) ready to go after it.

File: lib/BitcastUtils.cpp (hunk 1 above)
Comment (alan-baker) [reply lib/BitcastUtils.cpp:1097]: I'll add an extra test case that covers this.

**Comment by alan-baker** [comment]
> This is okay to go in, I have [this branch](https://github.com/rjodinchr/clspv/tree/pr/pre-memcpy-fix) ready to go after it.

There is another case to check that is a similar issue.

```
target datalayout = "e-p:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024"
target triple = "spir-unknown-unknown"

%struct.Line = type { i32, float, i32 }
%S = type { %struct.Line }

define void @test2(ptr addrspace(1) %data, i32 %n) {
entry:
  %gep1 = getelementptr inbounds %S, ptr addrspace(1) %data, i32 %n
  %gep2 = getelementptr inbounds i8, ptr addrspace(1) %gep1, i32 4
  store float 0.000000e+00, ptr addrspace(1) %gep2, align 4
  ret void
}
```

This case isn't fixed by this PR because I the logic elsewhere "pre-descends" through `%S`.

**Comment by rjodinchr** [comment]
Note that I reworked this part for the code in [this branch](https://github.com/rjodinchr/clspv/tree/pr/pre-memcpy-fix)
